---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm", "tar", "python3"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    
- name: "Copy files to EC2 instance"
  copy:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu

- name: "Unzip files for project"
  become: true
  shell: |
    cd /home/ubuntu
    tar -xzvf /home/ubuntu/backend.tar.gz
- name: Install Node
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
- name: Build Node
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build
- name: Start PM2
  become: true
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start



